// constants/errorCodes.js
module.exports = {
    USER_NOT_FOUND: "USER_NOT_FOUND",
    USER_EXISTS: "USER_EXISTS",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    MISSING_CREDENTIALS: "MISSING_CREDENTIALS",
    NOT_VERIFIED: "NOT_VERIFIED",
    ALREADY_VERIFIED: "ALREADY_VERIFIED",

    CODE_EXPIRED: "CODE_EXPIRED",
    INVALID_CODE: "INVALID_CODE",
    NO_VERIFICATION_CODE: "NO_VERIFICATION_CODE",
    RESET_NOT_CONFIRMED: "RESET_NOT_CONFIRMED",
    COOLDOWN_ACTIVE: "COOLDOWN_ACTIVE",

    INCORRECT_PASSWORD: "INCORRECT_PASSWORD",
};
